export const CtrCons = {
  SCALE_SET: 'SCALE_SET',
  TIME_SET: 'TIME_SET',
  TOTAL_TIME_SET: 'TOTAL_TIME_SET',
  SCROLL_TIME_SET: 'SCROLL_TIME_SET',
  TIMELINE_STATUS_SET: 'TIMELINE_STATUS_SET',
  LAYERS_SET: 'LAYERS_SET',
  END_SET: 'END_SET',
  DATA_INIT: 'DATA_INIT',
}
